### ISSUE TITLE
安装完成请在编辑器排除这两个目录防止编辑器被卡死

### ISSUE THREAD

**Issue by carlkyo** [laraveladmin-cn/laraveladmin#34]
請問"安装完成请在编辑器排除这两个目录防止编辑器被卡死"具體要怎麼做啊?
謝謝

**Comment by laraveladmin-cn** [comment]
1.编辑器打开项目
2.找到目录
3.鼠标悬停在指定目录上点击右键
4.选择"目录标记为"
5.点选"已排除"
![image](https://user-images.githubusercontent.com/76767270/218965038-51ebfa4f-0a9b-44a1-a7a3-8ac05a430680.png)

**Comment by carlkyo** [comment]
謝謝，
請問你那個是甚麼IDE啊
我在vscode和sublime text都找不到
謝謝

**Comment by laraveladmin-cn** [comment]
我们这边用的phpstorm
ide的编辑器
